// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dataapi.Model;

namespace dataapi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240407095607_UPDATE")]
    partial class UPDATE
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dataapi.Model.TBL_DISPENSELOG", b =>
                {
                    b.Property<Guid>("DISPENSELOGID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Type");

                    b.Property<string>("Unit");

                    b.HasKey("DISPENSELOGID");

                    b.ToTable("TBL_DISPENSELOG");
                });
#pragma warning restore 612, 618
        }
    }
}
